networks:
  laravel:

services:
  app:
    build:
      context: .
      dockerfile: build/apache/php-8.3/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
    depends_on:
      - mysql
      - mailhog
    networks:
      - laravel
      
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
