networks:
  laravel:

services:
  app:
    build:
      context: .
      dockerfile: build/apache/php-8.3/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    dns_search: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "5173:5173"
    environment:
      - XDEBUG_MODE=off
      - XDEBUG_START_WITH_REQUEST=no
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
      - ~/.ssh/id_ed25519_github:/root/.ssh/id_ed25519:ro
    depends_on:
      - mysql
      - mailhog
      - minio
    networks:
      - laravel
      
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - laravel

volumes:
  minio_data:
